---
apiVersion: batch/v1
kind: Job
metadata:
  name: rgw-verify
  labels:
    app: rgw-verify
  namespace: test-project
spec:
  completions: 4
  parallelism: 4
  completionMode: Indexed
  template:
    metadata:
      labels:
        app: rgw-verify
    spec:
      restartPolicy: Never
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: rgw-verify
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
        - labelSelector:
             matchLabels:
               app: rgw-verify
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: rgw-verify
        image: quay.io/mashetty/rgw_load:latest
        command:
        - /bin/bash
        - "-c"
        - "/opt/rgw_verify.py -d 3"
        workingDir: /mnt/target
        volumeMounts:
        - mountPath: /mnt/target
          name: rgw-load-volume
      volumes:
      - name: rgw-load-volume
        persistentVolumeClaim:
          claimName: rgw-load-pvc
